runtime: python39  # Set the correct Python version here.
instance_class: F2  # Choose the instance class based on your needs.
entrypoint: gunicorn -b :$PORT -w 2 -t 60 app:app

env_variables:
  SECRET_KEY: "2c4980313846217b1b163551414fda91e079a23154e7bf5c" #This is the key to encrypt cookies and other data for the user session
  PROJECT_ID: "starlit-complex-410801" # It was supposed to be the ID but I changed to project number and it worked
  PROJECT_NUMBER: "846835317031"
  TOPIC_ID: "prueba1"
  SECRET_ID: "web_client_secret"
  OTRO_FILE_ID: "1Fs4UPe668k6BKJC8p2opuNKJKD2JnrMVQZDvAb-VcjY" #multiday
  COYOTE_CASH_FILE_ID: "1q3sb5f8x0mkZIgDGtufsV13qFYKXT2fp3XI8Ot4UNF8"
  FAREHARBOR_FEE: 0.0367
  AIRBNB_FEE: 0.2
  URL: "http://starlit-complex-410801.uc.r.appspot.com"