runtime: python39  # Set the correct Python version here.
instance_class: F2  # Choose the instance class based on your needs.
entrypoint: gunicorn -b :$PORT -w 2 -t 60 app:app

env_variables:
  TZ: "America/Mexico_City"
  SECRET_KEY: "2c4980313846217b1b163551414fda91e079a23154e7bf5c" #This is the key to encrypt cookies and other data for the user session
  SECONDS_THRESHOLD_UPDATE: 2678000 #31 days
  NEW_ITINERARIO_RANGE: "!A1:M9"
  VIAJEROS_RANGE: "!A1:K40"
  EMAILS_RANGE: "!A2:B50"
  PAGOS_RANGE: "!B28:E43"
  PROJECT_ID: "640474142702" # It was supposed to be the ID but I changed to project number and it worked
  SECRET_ID: "coyote_workflow_webclient_secret" #Coyote
  LOG_FILE_ID: "1K-3zPuIOaePR0A1qjKf_kYJulsn-xxsd7KdvMReYAtA" #Coyote
  EMAIL_FILE_ID: "1OZAM8SeHwucAFNJjwEgzXBCRGGRVwLKYsmLe5X51V48" #Coyote
  ROOT_ID: "0ABvJcEQYHcHsUk9PVA" #Coyote